name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - uses: actions/checkout@v4
      
      # 2. Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      # 3. Instalar deps
      - run: |
          cd pwa/app/web && npm ci && cd ../../../
          cd pwa/app/api && npm ci && cd ../../../
      
      # 4. Testes
      - run: npm run test:e2e
      
      # 5. Build
      - run: cd pwa/app/web && npm run build
      
      # 6. Upload artefatos
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: playwright-report/